### ISSUE TITLE
Description box incorrectly always begins with blank line. Please remove it. Thanks.

### ISSUE THREAD

**Issue by jhb50** [benchen71/epub-metadata-editor#24]
Great job on this! Thanks.

**Comment by benchen71** [comment]
I am not sure what you are describing.  The description box is actually a small web browser so that the tags that can be used display correctly.  Yes, there is a space at the top of the box, but this is the page's margin, not a blank line.

Having said that, it might be possible to reduce the size of the margin.

**Comment by benchen71** [comment]
Fixed in version 1.4.9.

**Comment by jhb50** [comment]
Perfect. Thanks.
