### ISSUE TITLE
Error ordinal 459

### ISSUE THREAD

**Issue by Rotsblok** [benchen71/epub-metadata-editor#26]
I'm getting a Error message with the titel "E[ub Metadata Editor: EPubMetadataEditor.exe - Ordinal not found" with the text "the ordinal 459 could not be located in the dynamic link library urlmon.dll"
After clicking on "Ok" I'm getting it a few times, after that every thing works fine, until I load the next file. 
And the process of clicking on Ok to continue starts again

**Comment by Rotsblok** [comment]
It's on the latest download/release

**Comment by benchen71** [comment]
Does it happen with every EPUB file you try?  If not, can you please attach the problem EPUB file and explain the specific actions required to trigger the error.  (To attach an EPUB file, change the file extension from EPUB to JPG and then you can drag and drop the file into the comment box.)

**Comment by Rotsblok** [comment]
First time I tried your program I didn't install it, just ran is straight, after unpacking it, from the bin/Release dir. After that I installed it and problems aroze
Happens now to every EPUB file I try to open. As far as I can see, it's due to loading of the metadata fields. If a lot of fields are used, the more messages will come.
Will try to uninstall it and start from fresh and see what happens
![epubmetadataeditor](https://cloud.githubusercontent.com/assets/356422/17121557/e160b616-52d4-11e6-92fa-2f797125b801.jpg)

**Comment by Rotsblok** [comment]
Still got the problem after re-installing

**Comment by benchen71** [comment]
You attached the executable.  I need you to attach an example EPUB file that is causing the problem.

**Comment by benchen71** [comment]
Actually, after googling the error you are getting, I don't think the problem is with EPUBMetadataEditor.  I think it involves Internet Explorer.  My program apparently uses libraries which are somehow embedded in Internet Explorer (which handles web interactions for .net applications).  So if you have (perhaps) deselected Microsoft Explorer in the Windows Features (Control Panel -- Programs and Features -- Turn Windows features on or off) then that could be the problem.  Otherwise, various websites recommend running regsvr32 on some dll files.  (See the first answer on this page: http://answers.microsoft.com/en-us/windows/forum/windows_vista-performance/the-ordinal-459-could-not-be-located-in-the/d93d1cdf-763b-4403-bcc8-ca06d16f4f4a?auth=1).

**Comment by Rotsblok** [comment]
Still got it, after doing all the suggested sollutions.. Funny thing is  I only got the problem with this program. 
O well, it gonna be a long haul then to sort out the metadata of my 1k+ epubs...
Thnx anyway

**Comment by benchen71** [comment]
I'm sorry, it looks like there is nothing more I can do.
