### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by adanak** [benchen71/epub-metadata-editor#37]
Hi,

Thanks for my previously corrected bug. It works great!

But, there is another one for you. The opf file looks okay, but when I try to save whatever modification, it crashes.

Would you please check it out when you'll have some time?

Thanks a lot in advance!

**Comment by benchen71** [comment]
Got it.  When I get a chance, I'll look into it.

**Comment by benchen71** [comment]
I don't think I can do anything about this one.  The problem is being caused by the cover image file.  If you extract all the files in the EPUB (using 7-zip, for example), check out the date on cover.jpeg.  It's "5/08/2092 12:00 AM".  For some reason, this date is causing the zip library my program uses to bug out.

However, I will alter my program so that you get a sensible error message and ensure that the original file does not get corrupted or deleted.
