### ISSUE TITLE
Metadata not found – please check test file

### ISSUE THREAD

**Issue by BeckyDTP** [benchen71/epub-metadata-editor#39]
Hello,

Error message for the _test.epub_ file.
**ERROR: Metadata not found.
This ebook is malformed.**

I encounter this error very rarely (once the ca. 300 files).

[test.epub.zip](https://github.com/benchen71/epub-metadata-editor/files/2453483/test.epub.zip)

**Comment by benchen71** [comment]
Hi BeckyDTP,
The problem is occurring during the unzipping of the EPUB file.  The file "container.xml" (in the META-INF folder) doesn't have a date that the ZIP library my program uses can read properly.  So the unzip process crashes, resulting in the error.
Because the error occurs in the ZIP library, there isn't much I can do to fix this.  I can't even tell the user the name of the problem file.  However, if you encounter this error in the future, unzip the contents of the EPUB (I use 7-zip), delete the original EPUB, and then use 7-zip to create a new EPUB file.  It should now open correctly in EPUBMetadataEditor.
Sincerely,
Ben.

**Comment by brichmarsa** [comment]
Hi,
I had this issue even with files I already opened several times with Epubmetadataeditor without problem, but after the problem occurs, the file can't be normally open anymore even if I try the unzip/zip solution. Otherwise, I just find a solution, I open the "corrupted" file with Sigil, then save and close it. After that, the file is ok again.
Christophe.

**Comment by benchen71** [comment]
Hi Cristophe,
Thanks for sharing another possible solution!
Ben.
