### ISSUE TITLE
Problems with series_index

### ISSUE THREAD

**Issue by docjc** [benchen71/epub-metadata-editor#70]
Hi,
thats really a nice program you made.
Unfortunatelly I have some problems with series and series_index (please have a look on the epub attached) Instead of the correct index 01 it shows "Band" which is from the series. In other books you can find comletely different values/words like "cover" or something else. But all what is presented by the program is part of the meta data. Perhaps you can solve this problem ;)
rgs Jü 
[Casanova - Band 01 - Erinnerungen.zip](https://github.com/benchen71/epub-metadata-editor/files/9309930/Casanova.-.Band.01.-.Erinnerungen.zip)
x

**Comment by benchen71** [comment]
I've been sitting on version 1.9.1 for a while now, and it turns out it contains a fix for your exact problem. I will release version 1.9.1 shortly. When you get the new version, just open the problem file. You will still see "Band" in both the series name and the series index. Put "01" in the series index and save, and when you re-open the file everything should be correct.
