### ISSUE TITLE
[Question] find & replace support regex?

### ISSUE THREAD

**Issue by VegethB** [benchen71/epub-metadata-editor#76]
Example:
![image](https://user-images.githubusercontent.com/17975351/202154508-aa9a9768-aac5-43c3-b676-82c0d6e151b5.png)

`MKnR 20 -(g)- Southem Sea Riot`  -  `.* (\d+) -(\(\w\))- (.*)`
`The Irregular at Magic High School v20 - southem Sea Riot (g)`  -  `The Irregular at Magic High School v$1 - $3 $2`

Thanks

**Comment by benchen71** [comment]
I guess if there is a regex library I could plug in it's a possibility. But I don't have as much time for development at the moment, so it won't happen any time soon.

**Comment by benchen71** [comment]
The next version of the program will have regex in the find/replace batch operation.

However, I have not been able to test it, since I am not all that familiar with regex. I do know that you can get into a real mess if you don't know what you are doing. If you are able to test this functionality (on copies of your files, not originals!) and then open another issue if you should run into any problems.
