### ISSUE TITLE
Format "date" while renaming

### ISSUE THREAD

**Issue by TigersWay** [benchen71/epub-metadata-editor#86]
Hi,
Is there any way to format "date" - keep only year, for example - while building template/renaming a file?
Thanks!

**Comment by benchen71** [comment]
No there isn't. And I don't think it would be possible to implement, because it would require that a consistent date format has been used as the content for that field. I can imagine a lot of different possibilities:

YYYY
YYYY-MM-DD
YY-MM-DD
DD-MM-YYYY
DD-MM-YY
YYYY-DD-MM
YY-DD-MM
MM-DD-YYYY
MM-DD-YY

Working out which part of the string is the year would therefore be a non-trivial programming exercise, one that I simply don't have time to pursue.
