### ISSUE TITLE
Make the logic behind placing the `X` and `E` buttons to the right of the fields more obvious

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#94]
Currently, the main application window has 19 input fields. Three of them have **E** (Edit) buttons and one field has **X** [1] button.

As a user, I don't understand why these fields and only these fields have these buttons? Why can't I edit the value of a field with **E** button by simply placing the cursor in this field? And what is the purpose of the value clear button when this operation is performed in two steps (triple wedge and pressing `Delete`)? And if pressing the button is a means of accelerating the value deletion, shouldn't this button be next to each field of the window?

_[1] Apply Title Case to 'Title' (Hold SHIFT to Capitalise Every Word)_

**Comment by benchen71** [comment]
I can't do much more than what is provided by the tool tip message.

The E button next to the description allows editing the description text. This is necessary because the description text can contain markup tags. So a browser is used, not a textbox.

However, the other two E buttons do not change the content of their respective fields; they change what type of field it is. So the identifier field can display different types of identifier fields.

As for the small X next to the Title File As, it is not enough just to erase the contents since that leaves an empty tag in the OPF file. The X removes the tag completely.
